# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    paths:
      - 'software/**'
  pull_request:
    paths:
      - 'software/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    name: Lint code base using mypy (and pylint in future)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install ChipWhisperer
        run: >-
          python setup.py install
      - name: Install linters
        run: >-
          python -m pip install mypy
      - name: Run Mypy
        run: >-
          python -m mypy -p chipwhisperer
          
