name: Update private repo

on: push

jobs:
  trigger_action:
    name: Push dispatch
    runs-on: ubuntu-18.04
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run_test
          repo: newaetech/ChipWhisperer-Private-Tests
          token: ${{ secrets.PRIVATE_TEST_PUSH }}